version: "3.4"
x-hadoop-lab-common:
  &hadoop-lab-volumes
  volumes:
    - ${CONFIGS}/hadoop/core-site.xml:/etc/hadoop/core-site.xml
    - ${CONFIGS}/hadoop/hdfs-site.xml:/etc/hadoop/hdfs-site.xml
    - ${CONFIGS}/hadoop/mapred-site.xml:/etc/hadoop/mapred-site.xml
    - ${CONFIGS}/hadoop/yarn-site.xml:/etc/hadoop/yarn-site.xml
    - ${CONFIGS}/spark/spark-defaults.xml:/etc//spark/spark-defaults.xml

services:
  namenode:
    image: scala78/hadoop-namenode:${VERSION}
    container_name: namenode
    hostname: namenode
    restart: always
    volumes:
        - ${CONFIGS}/hadoop/core-site.xml:/etc/hadoop/core-site.xml
        - ${CONFIGS}/hadoop/hdfs-site.xml:/etc/hadoop/hdfs-site.xml
        - ${CONFIGS}/hadoop/mapred-site.xml:/etc/hadoop/mapred-site.xml
        - ${CONFIGS}/hadoop/yarn-site.xml:/etc/hadoop/yarn-site.xml
        - ${CONFIGS}/spark/spark-defaults.xml:/etc//spark/spark-defaults.xml
        - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=lab
    env_file:
      - ./hadoop.env   
  
  datanode:
    image: scala78/hadoop-datanode:${VERSION}
    container_name: datanode
    hostname: datanode
    restart: always
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
      - ${CONFIGS}/hadoop/core-site.xml:/etc/hadoop/core-site.xml
      - ${CONFIGS}/hadoop/hdfs-site.xml:/etc/hadoop/hdfs-site.xml
      - ${CONFIGS}/hadoop/mapred-site.xml:/etc/hadoop/mapred-site.xml
      - ${CONFIGS}/hadoop/yarn-site.xml:/etc/hadoop/yarn-site.xml
      - ${CONFIGS}/spark/spark-defaults.xml:/etc//spark/spark-defaults.xml
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env

  resourcemanager:
    image: scala78/hadoop-resourcemanager:${VERSION}
    container_name: resourcemanager
    hostname: resourcemanager
    restart: always
    <<: *hadoop-lab-volumes
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - ./hadoop.env

  nodemanager01:
    image: scala78/hadoop-nodemanager:${VERSION}
    container_name: nodemanager01
    hostname: nodemanager01
    restart: always
    <<: *hadoop-lab-volumes
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env

  nodemanager02:
    image: scala78/hadoop-nodemanager:${VERSION}
    container_name: nodemanager02
    hostname: nodemanager02
    restart: always
    <<: *hadoop-lab-volumes
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env

  historyserver:
    image: scala78/hadoop-historyserver:${VERSION}
    container_name: historyserver
    hostname: historyserver
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
      - ${CONFIGS}/hadoop/core-site.xml:/etc/hadoop/core-site.xml
      - ${CONFIGS}/hadoop/hdfs-site.xml:/etc/hadoop/hdfs-site.xml
      - ${CONFIGS}/hadoop/mapred-site.xml:/etc/hadoop/mapred-site.xml
      - ${CONFIGS}/hadoop/yarn-site.xml:/etc/hadoop/yarn-site.xml
      - ${CONFIGS}/spark/spark-defaults.xml:/etc//spark/spark-defaults.xml
    env_file:
      - ./hadoop.env  

  hadoop_proxy:
    image: datadog/squid
    container_name: hadoop_proxy
    hostname: hadoop_proxy
    restart: always
    ports:
      - 3128:3128      
    volumes:
      - hadoop_proxy:/var/log
  
  edgenode:
    image: scala78/hadoop-edgenode:${VERSION}
    container_name: edgenode
    restart: always
    hostname: edgenode
    ports:
      - "9922:22"
    volumes:
      - ${CONFIGS}/hadoop/core-site.xml:/etc/hadoop/core-site.xml
      - ${CONFIGS}/hadoop/hdfs-site.xml:/etc/hadoop/hdfs-site.xml
      - ${CONFIGS}/hadoop/mapred-site.xml:/etc/hadoop/mapred-site.xml
      - ${CONFIGS}/hadoop/yarn-site.xml:/etc/hadoop/yarn-site.xml
      - ${CONFIGS}/spark/spark-defaults.xml:/etc//spark/spark-defaults.xml
      - hadoop_edgenode:/home
      
  sparkhistoryserver:
    image: scala78/hadoop-sparkhistoryserver:${VERSION}
    container_name: sparkhistoryserver
    hostname: sparkhistoryserver
    restart: always
    <<: *hadoop-lab-volumes
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"

  livynode:
    image: scala78/hadoop-livynode:${VERSION}
    container_name: livynode
    hostname: livynode
    restart: always
    <<: *hadoop-lab-volumes
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    ports:
      - "8998:8998"

  huenode:
      image: gethue/hue:latest
      container_name: huenode
      hostname: huenode
      restart: always
      depends_on:
        - "mysqlnode"
      volumes:
        - ${CONFIGS}/hue/hue.ini:/usr/share/hue/desktop/conf/z-hue.ini
      ports:
        - "38888:8888"
  mysqlnode:
      image: mysql:5.7
      ports:
        - "33061:3306"
      container_name: mysqlnode
      hostname: mysqlnode
      command: --init-file /data/application/init.sql
      volumes:
        - data-mysql:/var/lib/mysql
        - ${CONFIGS}/hue/init.sql:/data/application/init.sql
      environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: hue

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
  hadoop_edgenode:
  hadoop_proxy:
  data-mysql:
