version: "3"

services:
  namenode:
    image: scala78/hadoop-namenode:${VERSION}
    container_name: namenode
    hostname: namenode
    restart: always
    # ports:
    #   - 9870:9870
    #   - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=lab
    env_file:
      - ./hadoop.env   
  
  datanode:
    image: scala78/hadoop-datanode:${VERSION}
    container_name: datanode
    hostname: datanode
    restart: always
    # ports: 
    #   - 9864:9864
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env

  resourcemanager:
    image: scala78/hadoop-resourcemanager:${VERSION}
    container_name: resourcemanager
    hostname: resourcemanager
    restart: always
    # ports:
    #   - 8088:8088
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - ./hadoop.env

  nodemanager01:
    image: scala78/hadoop-nodemanager:${VERSION}
    container_name: nodemanager01
    hostname: nodemanager01
    restart: always
    # ports:
    #   - 8042:8042
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env

  nodemanager02:
    image: scala78/hadoop-nodemanager:${VERSION}
    container_name: nodemanager02
    hostname: nodemanager02
    restart: always
    # ports:
    #   - 8242:8042
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env

  historyserver:
    image: scala78/hadoop-historyserver:${VERSION}
    container_name: historyserver
    hostname: historyserver
    restart: always
    # ports:
    #   - 8188:8188
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env  

  hadoop_proxy:
    image: datadog/squid
    container_name: hadoop_proxy
    hostname: hadoop_proxy
    restart: always
    ports:
      - 3128:3128      
    volumes:
      - hadoop_proxy:/var/log
  
  edgenode:
    image: scala78/hadoop-edgenode:${VERSION}
    container_name: edgenode
    restart: always
    hostname: edgenode
    ports:
      - "9922:22"
    volumes:
      - hadoop_edgenode:/home
      
  sparkhistoryserver:
    image: scala78/hadoop-sparkhistoryserver:${VERSION}
    container_name: sparkhistoryserver
    hostname: sparkhistoryserver
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"

  livynode:
    image: scala78/hadoop-livynode:${VERSION}
    container_name: livynode
    hostname: livynode
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    ports:
      - "8998:8998"

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
  hadoop_edgenode:
  hadoop_proxy:
